name: Windows Release

on:
  push:
    tags:
      - 'v*'  # 仅在推送 tag 时触发，如 v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary for release
        run: |
          Rename-Item target\release\simple-flappy-bird.exe simple-flappy-bird-windows.exe

      - name: Generate checksum
        run: |
          Get-FileHash simple-flappy-bird-windows.exe -Algorithm SHA256 | Format-List > checksum.txt

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            simple-flappy-bird-windows.exe
            checksum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
