name: Windows Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary
        run: Rename-Item target\release\flippy-bird.exe simple-flappy-bird-windows.exe

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: simple-flappy-bird-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
